### ISSUE TITLE
Change JSON Type Def into JS plugin?

### ISSUE THREAD

**Issue by angelozerr** [tylerwbell/tern-threejs#4]
Today tern cannot load external JSON Type Definition (we must wait that PR https://github.com/marijnh/tern/pull/528 will be accepted).

Perhaps you should transform your JSON Type Def into tern plugin?

**Comment by angelozerr** [comment]
I close this issue since now it's possible to load external JSON Type Definition. See https://github.com/marijnh/tern/pull/528

**Comment by angelozerr** [comment]
I reopen this issue, because it's more easy to have a plugin to load it with local HTML file instead of json which needs XMLHttpRequest (and problem with Cross Origin with Chrome).

Are you OK to do that?

**Comment by tylerwbell** [comment]
Done
