### ISSUE TITLE
Generation process

### ISSUE THREAD

**Issue by angelozerr** [tylerwbell/tern-threejs#6]
I create this issue because I'm a little lost with your generate.sh. At first it seems that you need to use io.js because jsdom need it.

After that https://github.com/tylerwbell/tern-threejs/blob/master/threejs.json is the result of your generation?

This JSON Type Definition doesn't work because you need spaces for the type parameter. Your defintion https://github.com/tylerwbell/tern-threejs/blob/master/threejs.json#L23 is for instance : 

```
fn(near:number, far:number, cubeResolution:number)
```

but it should be  : 

```
fn(near: number, far: number, cubeResolution: number)
```

**Comment by tylerwbell** [comment]
I am using io.js and the JSON type definition is still a work in progress.

**Comment by angelozerr** [comment]
> I am using io.js and the JSON type definition is still a work in progress.

Ok thank's. I'm waiting for that you finish your work to create PR form demos with CodeMirror + tests.
